package com.quine.backend.model;

public enum Role {
    ADMIN, //SUPER ADMIN , PRINCIPAL ETC
    STUDENT, //OBV STUDETNS
    FACULTY,//TEACHERS AND PROFESSORS
    STAFF,// DATA ENTERY GUY, SECURITY GUY AND OTHER STAFF
    EXAMINER // ALL GUYS FROM EXAM DEPARTMENT, THEY HAVE CONTROL FOR EXTERNAL MARKS
}