  spring.application.name=quine-backend

# Database Connection (This will basically tell backend where to connect database)
spring.datasource.url=jdbc:postgresql://localhost:5432/quine_db

## ( Replace with your Postgres Username)
spring.datasource.username=postgres

##(Replace this with your Postgres password)
spring.datasource.password=your_actual_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings (Ye database me tables apne aap banayega)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## Security and password
## (These fields are useless as we have already implemented our own security filter.)
spring.security.user.name=your_default_security_username
spring.security.user.password=your_default_security_password

## JWT AND SECURITY

application.security.jwt.secret-key=add_your_own_jwt_key_here
##Replace your JWT key with this
